baseurl = "/"
refLinksErrorLevel ="WARNING"
title = "DIVIDED DOCUMENTATION"
languageCode = "en-us"
paginate = "20" # Number of posts per page
theme = "mainroad"
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id
summaryLength = 20 # nastaveni delky summary v indexu na 20 slov

[Author] # Used in authorbox
  name = "Tomáš Dědič"
  bio = "VeryravenRetroroyalRoger"
  avatar = "img/avatar.png"

[Params]
  subtitle = "Tech howto, pancakes and syrup"
  description = "" # Site description. Used in meta description
  #copyright = "Tomas Dedic" # copyright holder, otherwise will use site title
  opengraph = true # Enable OpenGraph if true
  twitter_cards = false # Enable Twitter Cards if true
  readmore = false # Show "Read more" button in list if true
  authorbox = true # Show authorbox at bottom of pages if true
  toc = false # Enable Table of Contents
  post_navigation = true # Show post navigation at bottom of pages if true
  post_meta = ["date", "categories", "translations","tags"] # Order of post meta information. Use ["none"] to turn off completely.
  #postSections = ["post","data","tech"] # the section pages to show on home page and the "Recent articles" widget
  postSections = ["openshift","search"] 
  dateformat = "2006-01-02" # change the format of dates
  #mathjax = true # Enable MathJax
  #mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" # Specify MathJax path
  #mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
  customCSS = ["css/custom.css"] # Include custom CSS files

[Params.sidebar]
  home = "left" # Configure layout for home page
  list = false  # Configure layout for list pages
  single = false # Configure layout for single pages
  # Enable widgets in given order
  # widgets = ["search", "recent", "categories", "taglist", "social", "languages"]
  # widgets = ["recent", "categories", "taglist"]
  widgets = ["taglist", "recent"]

[Params.widgets]
  recent_num = 15 # Set the number of articles in the "Recent articles" widget
  tags_counter = true # Enable counter for each tag in "Tags" widget (disabled by default)

[Params.widgets.social]
  # Enable parts of social widget
  facebook = "username"
  twitter = "username"
  instagram = "username"
  linkedin = "username"
  telegram = "username"
  github = "username"
  gitlab = "username"
  bitbucket = "username"
  email = "example@example.com"
  google_plus = "profileid"


[markup]
defaultMarkdownHandler = "goldmark"
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "emacs"
    tabWidth = 4
  [markup.blackFriday]
    angledQuotes = true
    extensionsmask = ["autolink"]
    extensions = ["hardLineBreak"]
  [markup.goldmark]
     [markup.goldmark.extensions]
      # disable autoliks for URL
      linkify = false
