kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azure-file-ZRS
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0775
  - file_mode=0775
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl
  - cache=none
  - noperm
parameters:
  location: westeurope
  #skuName: Standard_LRS
  skuName: Standard_ZRS
  storageAccount: oshi4ckvrljn7zx
reclaimPolicy: Delete
volumeBindingMode: Immediate
