apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: toshi44-l9tcd
    machine.openshift.io/cluster-api-machine-role: infra
    machine.openshift.io/cluster-api-machine-type: infra
  name: toshi44-l9tcd-logging-westeurope3
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: toshi44-l9tcd
      machine.openshift.io/cluster-api-machineset: toshi44-l9tcd-logging-westeurope3
  template:
    taints:
    - effect: NoSchedule
      key: node-role/logging
    metadata:
      creationTimestamp: null
      labels:
        machine.openshift.io/cluster-api-cluster: toshi44-l9tcd
        machine.openshift.io/cluster-api-machine-role: infra
        machine.openshift.io/cluster-api-machine-type: infra
        machine.openshift.io/cluster-api-machineset: toshi44-l9tcd-logging-westeurope3
    spec:
      metadata:
        creationTimestamp: null
      providerSpec:
        value:
          apiVersion: azureproviderconfig.openshift.io/v1beta1
          credentialsSecret:
            name: azure-cloud-credentials
            namespace: openshift-machine-api
          image:
            offer: ""
            publisher: ""
            resourceID: /resourceGroups/toshi44-l9tcd-rg/providers/Microsoft.Compute/images/toshi44-l9tcd
            sku: ""
            version: ""
          internalLoadBalancer: ""
          kind: AzureMachineProviderSpec
          location: westeurope
          managedIdentity: toshi44-l9tcd-identity
          metadata:
            creationTimestamp: null
          natRule: null
          networkResourceGroup: toshi_vnet_rg
          osDisk:
            diskSizeGB: 128
            managedDisk:
              storageAccountType: Premium_LRS
            osType: Linux
          publicIP: false
          publicLoadBalancer: ""
          resourceGroup: toshi44-l9tcd-rg
          sshPrivateKey: ""
          sshPublicKey: ""
          subnet: toshi-worker-subnet
          userDataSecret:
            name: worker-user-data
          vmSize: Standard_D4S_v3
          vnet: toshi_vnet
          zone: "3"
