apiVersion: v1
baseDomain: azure.csint.cz
additionalTrustBundle: |
  # CSAS CA
  -----BEGIN CERTIFICATE-----
  # pem
  -----END CERTIFICATE-----
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform:
    azure:
      type: Standard_D4s_v3
      osDisk:
        # upravena velikost OS disku
        diskSizeGB: 256
  replicas: 3
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform:
    azure:
      type: Standard_D4s_v3
      osDisk:
        # upravena velikost OS disku
        diskSizeGB: 256
  replicas: 3
metadata:
  creationTimestamp: null
  name: oaz-dev
proxy:
 proxy:
   httpProxy: http://ngproxy-test.csint.cz:8080
   httpsProxy: http://ngproxy-test.csint.cz:8080
   noProxy: login.microsoftonline.com,management.azure.com,.blob.core.windows.net,.csint.cz
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  # rozsah pridelene VNETY
  - cidr: 10.88.232.0/23
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  azure:
    region: westeurope
    networkResourceGroupName: oaz-test-net-rg
    virtualNetwork: oaz-test-vnet
    controlPlaneSubnet: Master2
    computeSubnet: App2 
    # pouziti azure route table
    outboundType: UserDefinedRouting
    baseDomainResourceGroupName: openshift_az-dev-shared-rg
# typ publikace external vs internal 
publish: Internal
pullSecret: '{"auths":{"artifactory.csin.cz":{"auth":"b2NwOlRyZTVaaXpxbEdKT1NZdzhCUVZ5ZGFXbjk0eVZNZg==","email":"myemail"}}}'
sshKey: |
  # ssh klic pro pristup na uzivatele core jednotlivych nodu
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCt7DDUmaM1mMn9nW8L8iT6Ivh59k9Hq/QsljQV5iuKT9emRHCgbwoTBAlZUqq+ymyqlGut1ZWhH7hVZlCx0Aq5q232pspwJ5+pZ8HkfgU9RNSgvUrh0/jsZBZqpBIQ+gQKAWABVSbB0oMSUz+9bkiiFF/AyEWpmiY34U3BFNalckH1pEmA7xD0uzB+LO0J6jwsIYaBWgHZmrDhQKa/4wrt6Dy06ZQm2QfIKmTT7CV1g8v5Ftf+yG7hgHS7zm+Citlq/Pnzd5gggs42DnKCJICV/viGkRjJkX8XsFLCHsfAOBqw8hTRXMtBVBA2jMUT+q6wAbV5BiQWZdbk4/MZJqAVlQXYcczz9u4TBXP1bHlkj/r4gqwzakLIVZE4eEnb0kX0DuNnKy7wN5U2iyHkox0M6021vuDq9ARmbYqty/5VwgvFCt9YHNvxr0bP8Zz3bpEf8JrAnOGHjbPhnVh0ZGFO1EWMbgTT9DpbnHJfcK3AJaFBhyD8jtbJgsKOjcVqmYrJhhAKwW7vqu54zCit510svOu7rBUegRr4z+MgbTuXXspUcqWXSBjBiAmKptOpbWt0x15oj6M/wapc2EnjvCkSvo42iImX7rPD3F62AK8ByDsbBxU8yLTsjiv8TTJAGGE77ir22JG1Qg2gElg7c4lWkjJ4Srsh8Dl+Pjq5znoAWQ== bastion-oaz-dev
imageContentSources:
  # odkaz na artifactory remote repo
- mirrors:
  - artifactory.csin.cz/docker-quay/openshift-release-dev/ocp-release
  source: quay.io/openshift-release-dev/ocp-release
- mirrors:
  - artifactory.csin.cz/docker-quay/openshift-release-dev/ocp-v4.0-art-dev
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
