apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv0001
spec:
  storageClassName: ""
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: //xxxnfsxxx/pokusnynfsshare
    server: xxxnfsxxx.file.core.windows.net
  persistentVolumeReclaimPolicy: Retain
