---
version: '3.1'

networks:
  monitoring:
    external: true

volumes:
  grafana_data: {}

services:
  grafana:
    image: grafana/grafana:9.0.2
    networks:
      - monitoring
    user: "104"
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    restart: always
