auth_enabled: false

server:
 http_listen_port: 3100

memberlist:
 join_members:
  - loki:7946

common:
  replication_factor: 1
  path_prefix: /var/lib/enterprise-logs
  ring:
    kvstore:
      store: memberlist

s3_storage_config:
  endpoint: minio:9000
  insecure: true
  bucketnames: loki
  access_key_id: loki
  secret_access_key: XacKxpaF8VwDUqPmwWuw08kdHAMaIv9t
  s3forcepathstyle: true

ingester:
  chunk_idle_period: 1h
  max_chunk_age: 1h
  chunk_retain_period: 30s

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://alertmanager:9093

limits_config:
  ingestion_rate_mb: 9
  ingestion_burst_size_mb: 12
