auth_enabled: false

server:
  http_listen_port: 3100
#  http_server_read_timeout: 10m
#  http_server_write_timeout: 10m
#  http_server_idle_timeout: 10m
  grpc_server_max_recv_msg_size: 8388608

memberlist:
  join_members:
    - loki:7946

limits_config:
  per_stream_rate_limit: 0
  ingestion_rate_mb: 10
  ingestion_burst_size_mb: 12
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  split_queries_by_interval: 10m

query_range:
  cache_results: true

schema_config:
  configs:
    - from: 2021-08-01
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: index_
        period: 24h

common:
  path_prefix: /loki
  replication_factor: 1
  storage:
    s3:
      s3forcepathstyle: true
      region: "dc1"
      bucketnames: "loki"
      endpoint: "minio:9000"
      access_key_id: "loki"
      secret_access_key: "XacKxpaF8VwDUqPmwWuw08kdHAMaIv9t"
      insecure: true
  ring:
    kvstore:
      store: memberlist

ruler:
  alertmanager_url: http://localhost:9093
  storage:
    s3:
      bucketnames: loki

ingester:
  chunk_idle_period: 30m #any chunk not recieving new logs in this time will be flushed
  max_chunk_age: 1h #chunks older then this time will be flushed

compactor:
#  working_directory: /data/compactor
  shared_store: s3
  compaction_interval: 5m

