# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Thanos
    orgId: 1
  - name: Loki
    orgId: 1

# list of datasources to insert/update depending
# whats available in the database
datasources:
  - id: 1
    orgId: 1
    name: Thanos
    type: prometheus
    typeName: Prometheus
    typeLogoUrl: public/app/plugins/datasource/prometheus/img/prometheus_logo.svg
    access: proxy
    url: http://thanos-query-frontend:10901
    user: ''
    database: ''
    basicAuth: false
    isDefault: true
    jsonData:
      graphiteVersion: '1.1'
      tlsAuth: false
      tlsAuthWithCACert: false
    readOnly: false
  - id: 2
    orgId: 1
    name: Loki
    type: loki
    typeName: Loki
    typeLogoUrl: public/app/plugins/datasource/loki/img/loki_icon.svg
    access: proxy
    url: http://loki:3100
    user: ''
    database: ''
    basicAuth: false
    isDefault: false
    jsonData: {}
    readOnly: false
