apiVersion: logging.openshift.io/v1
kind: ClusterLogging
metadata:
  name: instance
  namespace: openshift-logging
spec:
  managementState: Managed
  logStore:
    type: elasticsearch
    elasticsearch:
      nodeSelector:
        node.purpose: logging
      tolerations:
      - key: "node-role"
        operator: "Equal"
        value: "logging"
        effect: "NoSchedule"
      nodeCount: 1
      redundancyPolicy: ZeroRedundancy
      storage:
        storageClassName: managed-premium
        size: 200G
      resources:
          limits:
            cpu: "800m"
            memory: "8Gi"
          requests:
            cpu: "100m"
            memory: "8Gi"
  visualization:
    type: kibana
    kibana:
      nodeSelector:
        node.purpose: logging
      tolerations:
      - key: "node-role"
        operator: "Equal"
        value: "logging"
        effect: "NoSchedule"
      replicas: 1
      resources:
        limits:
          memory: 2Gi
        requests:
          cpu: 100m
          memory: 1Gi
  curation:
    type: curator
    curator:
      tolerations: 
       - key: "node-role"
         operator: "Equal"
         value: "logging"
         effect: "NoSchedule"
      resources:
        limits:
          memory: 200Mi
        requests:
          cpu: 100m
          memory: 100Mi
      schedule: "*/5 * * * *"
  collection:
    logs:
      type: fluentd
      fluentd:
        tolerations: 
        - key: "node-role"
          operator: "Equal"
          value: "logging"
          effect: "NoSchedule"
        resources:
          limits:
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 1Gi
