---
version: '3.1'

networks:
  monitoring:
    external: true

volumes:
  minio_data_disk1:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /srv/data/minio/disk1

services:
  minio:
    image: minio/minio:RELEASE.2022-07-17T15-43-14Z
    networks:
      - monitoring
    volumes:
      - minio_data_disk1:/data1
    entrypoint: sh
    command: -c 'minio server /data1 --console-address ":9001"'
    environment:
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=administrator
      - MINIO_PROMETHEUS_AUTH_TYPE=public
    ports:
      - 9000:9000
      - 9001:9001
    restart: always
