name: generate_hugo_site

on:
  push:
    branches:
      - master

jobs:
  build:
    env:
      image_name: hugo
    runs-on: ubuntu-18.04
    steps:
      - name: Inform other repo that build is success
        uses: actions/checkout@v2
        #checkout
        with:
          repository: tomasdedic/ocpdocCD.git
          token: ${{ secrets.PERSONAL_TOKEN }} # `GitHub_PAT` is a secret that contains your PAT
          path: test

      - uses: actions/checkout@v2
      - run: |
          cd test
          date > test/generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
      # - name: Delete oldest package
      #   if: ${{ steps.build_and_publish.conclusion == 'success'}}
      #   uses: actions/delete-package-versions@v1
      #   with:
      #     package-name: hugogen
