name: generate_hugo_site

on:
  push:
    branches:
      - master

jobs:
  build:
    env:
      image_name: hugo
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          submodules: true

      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_URI }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and publish image to Quay
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: quay.io/dedtom/hugo:latest
