name: generate_hugo_site

on:
  push:
    branches:
      - master

jobs:
  build:
    env:
      image_name: hugo
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          submodules: true
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          # registry: docker.pkg.github.com
          username: dedtom@gmail.com
          password: ${{ secrets.PERSONAL_TOKEN }}

      - id: get-id
        run: |
          id=$(echo ${GITHUB_SHA} | cut -c 1-4)
          echo ${GITHUB_SHA}
          echo $id
          echo "::set-output name=sha::$id"

      - name: Build and publish image to Github
        id: build_and_publish
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./Dockerfile
          tags: ghcr.io/tomasdedic/ocpdoc/hugogen:${{steps.get-id.outputs.sha}}
          # tags: docker.pkg.github.com/tomasdedic/ocpdoc/hugogen:${{steps.get-id.outputs.sha}}
          # secrets: |
            # GIT_AUTH_TOKEN=${{ secrets.PERSONAL_TOKEN }}

      - name: Inform other repo that build is success
        if: ${{ steps.build_and_publish.conclusion == 'success' }}
        uses: actions/checkout@v2
        with:
          repository: tomasdedic/ocpdocCD
          token: ${{ secrets.PERSONAL_TOKEN }} # `GitHub_PAT` is a secret that contains your PAT
          path: test

      - uses: actions/checkout@v2
      - run: |
          cd test
          date > test/generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
      # - name: Delete oldest package
      #   if: ${{ steps.build_and_publish.conclusion == 'success'}}
      #   uses: actions/delete-package-versions@v1
      #   with:
      #     package-name: hugogen
