name: generate_hugo_site

on:
  push:
    branches:
      - master

jobs:
  build:
    env:
      image_name: hugo
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          submodules: true

      - name: Build and publish image to Quay
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          path: ${{ env.context }}
          registry: ${{ secrets.REGISTRY_URI }}
          repository: ${{ secrets.REGISTRY_REPOSITORY }}/${{ env.image_name }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          tags: latest
